spring:
  datasource:
    url: jdbc:h2:mem:bookAppDb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS bookAppDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    name: bookAppDb
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      format_sql: true
      show-sql: true
      default_schema: bookAppDb
admin:
  login: admin
  password: admin
server:
  port: 9090
feign:
  url: http://localhost:${server.port}
postman:
  url: http://localhost:${wiremock.server.port}
